#pragma once
#define IMGUI_DEFINE_MATH_OPERATORS
#include <algorithm>
#include <any>
#include <chrono>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>   
#include <random>
#include <sstream>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>        
#include <vector>
#include <cmath>
#include <functional>    
#include <type_traits> 
#include <filesystem>   

#include <wtypes.h>
#include <windows.h>
#include <psapi.h>
#include <conio.h>
#include <shellapi.h>
#include <processthreadsapi.h>

#include <jni.h>
#include <jvmti.h>